# Data, see solver-perf-processed.results
# Generated by `generate_table.rb r`
Size = c(9, 82, 140, 304, 574, 775, 850, 1070, 1557, 1965)
Time = c(2.0, 3.35, 9.0, 67.2, 408.25, 1014.9, 1309.3, 2601.15, 7844.4, 16175.65)

# Model computation
Size2 <- Size^2
Size3 <- Size^3
cubic.model <-lm(Time ~ Size + Size2 + Size3)
summary(cubic.model)

## Model: 2.393e-06*x**3 + (-7.500e-04)*x**2 + 4.696e-01*x + (-3.422e+01)
## R-squared:  0.9999
